const fullSymbolsList =
    'BTC,ETH,SOL,SRM,SUSHI,SXP,FTT,YFI,LINK,HGET,CREAM,FRONT,AKRO,UNI,BVOL,IBVOL,AAVE,FIDA,HOLY,SECO,RSR,CEL,COMP,GRT,PAXG,KIN,USDT,USDC,MAPS,PERP,RAY,OXY,COPE,ROPE,STEP,MEDIA,TULIP,MER,SLIM,SNY,APEX,SLRS,LIQ,SBR,FAB,ORCA,DXL,MNGO,SUNNY,GOFX,CRY,CAVE,ATLAS,POLIS,DFL,MSOL,LIKE,PRISM,WOOF,XTAG,CRWNY,gSAIL,SAMU,GST,BRZ,CYS,CWAR,REAL,MBS,AART,OOGI,CHICKS,RACEFI,SLND,UPS,UNQ,PORT,IN,ABR,RIN,JET,UXP,DATE,SAIL,YARD,SOLC,SOLPAD,BTSL,MOLA,SWARM,DAWG,LEONIDAS,CHEEMS,SDOGE,WIPE,NAXAR,PRT,SHILL,BOP,ASH,SOLAB,GST,SLX,KURO,CRP,AURY,BNB,LUNA,AVAX,renDOGE,SHIB,SAND,MANA,DYDX,STREAM,';

//removed tokens for cmc: AXSET,FANT,LQID,MATICPO,SOALEPH,SOHNT,SOHXRO,SOKEEP,SOLUA,SOMATH,SOSWAG,SOTOMO,SOUBXT,XCOPE

const symbolList1 =
    'BTC,ETH,SOL,SRM,SUSHI,SXP,FTT,YFI,LINK,HGET,CREAM,FRONT,AKRO,UNI,BVOL,IBVOL,AAVE,FIDA,HOLY,SECO,RSR,CEL,COMP,GRT,PAXG,KIN,USDT,USDC,MAPS,PERP,RAY,OXY,COPE,ROPE,STEP,MEDIA,TULIP,MER,SLIM,SNY,APEX,SLRS,LIQ,SBR,FAB,ORCA,DXL,MNGO,SUNNY,GOFX,STREAM';

const symbolList2 =
    'CRY,CAVE,ATLAS,POLIS,DFL,MSOL,LIKE,PRISM,WOOF,XTAG,CRWNY,gSAIL,SAMU,GST,BRZ,CYS,CWAR,REAL,MBS,AART,OOGI,CHICKS,RACEFI,SLND,UPS,UNQ,PORT,IN,ABR,RIN,JET,UXP,DATE,SAIL,YARD,SOLC,SOLPAD,BTSL,MOLA,SWARM,DAWG,LEONIDAS,CHEEMS,SDOGE,WIPE,NAXAR,PRT,SHILL,BOP,ASH';

const symbolList3 =
    'SOLAB,GST,SLX,KURO,CRP,AURY,BNB,LUNA,AVAX,renDOGE,SHIB,SAND,MANA,DYDX';

export { fullSymbolsList, symbolList1, symbolList2, symbolList3 };